### ISSUE TITLE
Windows10 - Error port-forwarding web (30080 -> 8080): Unable to listen on port 30080

### ISSUE THREAD

**Issue by jechrzFoko** [tilt-dev/tilt#5792]
### Expected Behavior
Port forwarding should work smoothly in windows machines

### Current Behavior
* Getting the following error when we updated tilt to v0.29 on windows 10 machines. This doesn't happen on our Mac's:
```
Reconnecting... Error port-forwarding...(30080 -> 8080): Unable to listen on port 30080: Listeners failed to create with the following errors: [unable to create listener: Error listen tcp6 [::1]:30080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.]
```

* Potentially related to this [ticket ](https://github.com/tilt-dev/tilt/issues/5043) 🤔

### Steps to Reproduce
* upgraded to tilt v0.29
* updated k8s_resources in tiltfile to allow it to handle port forwarding (k8s_resource(workload='web', port_forwards=['30080:8080'], labels='Front-end')

#### `tilt doctor` Output
```
Tilt: v0.29.0, built 2022-05-06
System: windows-amd64
---
Docker
- Host: npipe:////./pipe/docker_engine
- Server Version: 20.10.14
- API Version: 1.41
- Builder: 2
- Compose Version: v2.4.1
---
Kubernetes
- Env: docker-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.22.5
- Cluster Local Registry: none
```

#### About Your Use Case
* Our frontend service starts failing to connect to BE and throws network errors; would like to have no failures when using our web service and no issues with port forwarding when on a windows machine
* Are there any extra setup steps for windows users to get this sorted out?

**Comment by nicksieger** [comment]
Thanks for reporting! Yeah, since the fix for the ticket you mentioned Tilt will attempt to listen on both ipv4 and ipv6 addresses. Does Tilt behave any differently if you run it as `tilt up --host 127.0.0.1`? To see if we can get it to only listen on ipv4 localhost?

**Comment by nicks** [comment]
I think you might be overthinking this.

This is the standard windows error message for: "sorry, you already have another server listening on that port".

It's pretty easy to reproduce by doing

```
python3 -m http.server 30080--bind 127.0.0.1
```

before starting tilt. You can also use `netstat -A` to figure out what servers are currently taking up ports on Windows.

To answer your meta question - no, there are typically no extra setup steps on windows to get port-forwarding working. If the port is available, it should Just Work.

**Comment by jechrzFoko** [comment]
> I think you might be overthinking this.
> 
> This is the standard windows error message for: "sorry, you already have another server listening on that port".
> 
> It's pretty easy to reproduce by doing
> 
> ```
> python3 -m http.server 30080 --bind 127.0.0.1
> ```
> 
> before starting tilt. You can also use `netstat -A` to figure out what servers are currently taking up ports on Windows. Can you confirm that there are no other services taking up that port? (or try another port?)
> 
> To answer your meta question - no, there are typically no extra setup steps on windows to get port-forwarding working. If the port is available, it should Just Work.

running the python command above does not throw the error message (before tilt start) which did confirm that the port is available; additionally we did find out that because our kube cluster is setup to have port forwarding on top of the tilt port fowarding, we realized it was causing pf conflict (which seems to be handled gracefully on a mac setup vs windows)

> Thanks for reporting! Yeah, since the fix for the ticket you mentioned Tilt will attempt to listen on both ipv4 and ipv6 addresses. Does Tilt behave any differently if you run it as `tilt up --host 127.0.0.1`? To see if we can get it to only listen on ipv4 localhost?

running `tilt up --host 127.0.0.1` did make the pf error message go away; _however_ on our current setup, ipv6 is disabled  🤔

**Comment by nicksieger** [comment]
Looks like the code path when no host is specified and it defaults to "localhost" does not go through the `getListenableAddresses` function from #5245. Should be fixed by #5795.

**Comment by nicksieger** [comment]
A workaround in the meantime would be to specify `127.0.0.1:30080:8080` in your port forward spec.

**Comment by nicksieger** [comment]
@jechrzFoko Actually, I'm curious if running `kubectl port-forward deployment/web 30080:8080` fails in the same way on your windows machines?

**Comment by nicks** [comment]
@jechrzFoko what mechanism are you using to disable ipv6? i tried a few different network configurations on my windows box and wasn't able to repro this.

**Comment by jechrzFoko** [comment]
> @jechrzFoko what mechanism are you using to disable ipv6? i tried a few different network configurations on my windows box and wasn't able to repro this.

On Windows 10 Pro (might differ a bit in other versions) under control panel > network and internet > network connections, select your network connection for your local and right click on properties, then there will be a list of checkboxes to disable connection configurations. I've unchecked the box for ipv6 to disable it (and to be sure, restart the machine as well. Can also run ipconfig to check if you only have an ipv4 address after restart).

![image](https://user-images.githubusercontent.com/68392474/167697236-158132b5-2d4e-4677-b403-28cea0b72c7b.png)

**Comment by nicksieger** [comment]
I'm curious what this Go program outputs on Windows:

```go
package main

import (
	"fmt"
	"net"
	"os"
)

func main() {
	listener, err := net.Listen("tcp4", net.JoinHostPort("127.0.0.1", "0"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "tcp4 error: %v\n", err)
		return
	}
	defer listener.Close()
	listenerAddress := listener.Addr().String()
	_, localPort, _ := net.SplitHostPort(listenerAddress)
	v6listener, err := net.Listen("tcp6", net.JoinHostPort("::1", localPort))
	if err != nil {
		fmt.Fprintf(os.Stderr, "tcp6 error: %v\n", err)
		return
	}
	fmt.Printf("Listened to port %s successfully on both 127.0.0.1 and ::1\n", localPort)
	v6listener.Close()
}
```

**Comment by jechrzFoko** [comment]
> I'm curious what this Go program outputs on Windows:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"net"
> 	"os"
> )
> 
> func main() {
> 	listener, err := net.Listen("tcp4", net.JoinHostPort("127.0.0.1", "0"))
> 	if err != nil {
> 		fmt.Fprintf(os.Stderr, "tcp4 error: %v\n", err)
> 		return
> 	}
> 	defer listener.Close()
> 	listenerAddress := listener.Addr().String()
> 	_, localPort, _ := net.SplitHostPort(listenerAddress)
> 	v6listener, err := net.Listen("tcp6", net.JoinHostPort("::1", localPort))
> 	if err != nil {
> 		fmt.Fprintf(os.Stderr, "tcp6 error: %v\n", err)
> 		return
> 	}
> 	fmt.Printf("Listened to port %s successfully on both 127.0.0.1 and ::1\n", localPort)
> 	v6listener.Close()
> }
> ```
> 
> Going to try it in a VM with/without IPv6 and see if I see the same error as the OP.

here's a run on my pc with ipv6 disabled:
![image](https://user-images.githubusercontent.com/68392474/167705401-6e64710d-5b53-44b7-8c30-2cb79aa9f052.png)

**Comment by nicksieger** [comment]
Yeah, it's strange, I see the same thing with and without ipv6 disabled. And if you modify line 10 to use port `"30080"` does it still work for you?

**Comment by nicksieger** [comment]
I merged #5795 with some updates to the portforwarding code from the k8s client-go upstream but I'm not certain it will eliminate your issue. If you're able and would like to try with those changes, you can clone tilt and build as mentioned in our [CONTRIBUTING](https://github.com/tilt-dev/tilt/blob/master/CONTRIBUTING.md#build) guide.

**Comment by nicks** [comment]
fwiw, still was not able to reproduce this, even after unchecking the ipv6 box above and restarting :thinking: :thinking: :thinking:

**Comment by jechrzFoko** [comment]
> Yeah, it's strange, I see the same thing with and without ipv6 disabled. And if you modify line 10 to use port `"30080"` does it still work for you?

yup still works with changing the port to 30080.

For the time being, we have switched our config to use the recommended workaround (adding 127.0.0.1:30080:8080  to the port_forward spec); we're ok to wait until #5795 is on an available release to revisit

**Comment by jechrzFoko** [comment]
@nicksieger we tried tilt v0.30 and the error still exists even with the changes from #5795. From our side, we decided to turn off port forwarding in the tiltfile for the services having the pf issues (specifically our web and ingress services) and decided to handle port forwarding via kube nodeports . It looks like the error is valid as @nicks  mentioned, having multiple areas in the infrastructure attempting to port forward causes conflict on assigning ports. Closing issue as we've resolved it from our end and no further actions required.
